# Generated by Django 5.2.13 on 2026-04-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
            ],
            options={
                'verbose_name': 'Підписник',
                'verbose_name_plural': 'Підписники',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Сесія')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано о')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Елемент кошика',
                'verbose_name_plural': 'Кошик',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Сесія')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Оцінка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Оцінка товару',
                'verbose_name_plural': 'Оцінки товарів',
                'unique_together': {('product', 'session_key')},
            },
        ),
    ]
